---
title: "Lab 02 - Plastic waste"
author: "Léa Blais"
date: "15 septembre 2025"
output: github_document
---

## Chargement des packages et des données

```{r load-packages, message=FALSE}
library(tidyverse) 
```

```{r load-data, message=FALSE}
plastic_waste <- read_csv("data/plastic-waste.csv")
```

```{r load-data, message=FALSE}
ggplot(data = plastic_waste, aes(x = plastic_waste_per_cap)) +
  geom_histogram(binwidth = 0.2)
```
Commençons par filtrer les données pour retirer le point représenté par Trinité et Tobago (TTO) qui est un outlier.

```{r filter-data, message=FALSE}
plastic_waste <- plastic_waste %>%
  filter(plastic_waste_per_cap < 3.5)
```


## Exercices

### Exercise 1

```{r plastic-waste-continent}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap)) +
  geom_histogram(binwidth = 0.25) +
  facet_wrap(~ continent)
```

### Exercise 2

```{r plastic-waste-density}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap)) +
  geom_density()
```
```{r plastic-waste-density}
ggplot(plastic_waste, aes(x = plastic_waste_per_cap, color = continent)) +
  geom_density()
```
Réponse à la question...

### Exercise 3

Boxplot:

```{r plastic-waste-boxplot}
# insert code here
```

Violin plot:

```{r plastic-waste-violin}
# insert code here
```

Réponse à la question...

### Exercise 4


```{r plastic-waste-mismanaged}
# insert code here
```

Réponse à la question...

### Exercise 5


```{r plastic-waste-population-total}
# insert code here
```

```{r plastic-waste-population-coastal}
# insert code here
```

Réponse à la question...

## Conclusion

Recréez la visualisation:

```{r recreate-viz}
# insert code here
```
